let c = Context()
println("\(c.isAuthorized), \(c.userId)")
c.changeStateToAuthorized(userId: "admin")
println("\(c.isAuthorized), \(c.userId)")
c.changeStateToUnauthorized()
println("\(c.isAuthorized), \(c.userId)")